### ISSUE TITLE
Grand Finale

### ISSUE THREAD

**Issue by wschella** [ZeusWPI/aichallenge#111]
- [x] Buy prizes, see #62 
- [x] Make some interesting maps
- [x] Something something brackets

**Comment by wschella** [comment]
We have prizes from @NoctuaNivalis and a winner's cup.

**Comment by Procrat** [comment]
We can use a bracket system from [here](http://www.printyourbrackets.com/double-elimination-tournament-brackets.html). We don't know the number of participants op front though. (Maybe next year, we could have participants subscribe.)

**Comment by wschella** [comment]
It has happened. Thanks to everyone who helped and participated.
