### ISSUE TITLE
Mention somewhere python 3 will be default

### ISSUE THREAD

**Issue by SirDestrox** [ZeusWPI/aichallenge#39]

**Comment by Procrat** [comment]
We should probably also mention what versions of interpreters and compilers are available.

**Comment by SirDestrox** [comment]
Good idea, I propose we keep that info in a seperate file in the repo where we can refer to in other sections.

**Comment by Procrat** [comment]
Btw, it'll run on a Debian machine, so `python` will alias to `python2` :/

**Comment by Procrat** [comment]
How to run for different Python versions should be clear now from the info added in 210118b2232a53be545deb0d8a1c7a7d7a728835 (ranker branch)
