### ISSUE TITLE
Allow bots to be deleted while being used in the ranker

### ISSUE THREAD

**Issue by SirDestrox** [ZeusWPI/aichallenge#60]
People can practically never delete a bot, since it's very actively used in the ranker. Deleting a bot causes errors in the session.commit() statement, which causes a session rollback. Bots are never deleted.

**Comment by feliciaan** [comment]
Maybe add an deleted field to the bot, so you can check if the bot is deleted. Deleted bots shouldn't be shown in the views, and shouldn't be used in new matches.

**Comment by SirDestrox** [comment]
This would cause a lot of trouble with unique naming. You just deleted your bot, but can't reuse it's name because it isn't actually deleted. This method seems very error prone, it should be possible to effectively purge all bot data and files from the system.

**Comment by SirDestrox** [comment]
Updates also do not remain, they appear to have applied, but it seems after a while they are undone.

**Comment by Procrat** [comment]
This should be fixed, I think. I tested this. The ranker now rolled back the match.

**Comment by SirDestrox** [comment]
I tested this as well, can confirm.
