### ISSUE TITLE
Buy prizes for the finale

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/aichallenge#62]
Ideas for cool prizes? :smile:

**Comment by NoctuaNivalis** [comment]
I've donated some leftover prizes (small fysical puzzles) from the VWO.

**Comment by Procrat** [comment]
We still need 1 supercool prize for the winner. Ideas anyone?

**Comment by Silox** [comment]
Something with real robots? Some kind of pi/arduino/frequently used robot controller board?

**Comment by Procrat** [comment]
Sounds cool! I was thinking of some O'Reilly book on artificial intelligence, but this is probably cooler :smile:

**Comment by Silox** [comment]
Books are perhaps more useful (cfr the pi I have laying in a shelf for the
past 4 years)

2016-04-06 12:33 GMT+02:00 Stijn Seghers <notifications@github.com>:
