### ISSUE TITLE
Announce new website + finale

### ISSUE THREAD

**Issue by Procrat** [ZeusWPI/aichallenge#63]
- [x] Write blogpost
- [x] Announce on Zeus + Cicero mailing list
- [x] Announce on Facebook page
- [x] Announce on Twitter
- [ ] Announce on Facebook groups

Summary: We made a visualizing ranking website. (First?) codenight on Tuesday 12th April. We will have a finale on xx May.

**Comment by SirDestrox** [comment]
I propose we do a full testing round on the production server first.

**Comment by Procrat** [comment]
We've been testing the last day. As time is running out for the bot writers, I'd suggest we go ahead and announce it and deal with possible problems ad hoc.

**Comment by Procrat** [comment]
Nevermind, we already have an error. The match log file doesn't get written for some reason.
`FileNotFoundError: [Errno 2] No such file or directory: '/home/battlebots/production/battlebots/matches/52549'`

**Comment by Silox** [comment]
> Badass Battle Bots is back! Now with an updated website, match visualiser and realtime rankings! Head over to https://zeus.ugent.be/battlebots to enter your bot. 
> This Tuesday (12th of April), we're also organising the first official BBB codenight, where you can code your own battle bot, discuss strategies, trash-talk your opponents and/or ask for advice when you’re stuck! See you Tuesday, 18h @ V3, S9, Campus Sterre!

**Comment by Silox** [comment]
I can't do the groups as I'm not a part of them anymore, so I'll leave that to you @Procrat and @SirDestrox :D

**Comment by SirDestrox** [comment]
Will do tomorrow.

**Comment by Procrat** [comment]
Codenight is happening.
