### ISSUE TITLE
things break when bot names contain 'special' characters

### ISSUE THREAD

**Issue by JensTimmerman** [ZeusWPI/aichallenge#72]
you get things like 

`inputparser%201.1 does not exist or does not belong to jens`

or you can successfully delete them, but they are still there...

**Comment by EMerckx** [comment]
This issue also exists with other characters, like dollar signs.

    xXxPu%24%24yd3%24troy3r-GAYFART-0.1xXx does not exist or does not belong to Gayfart

**Comment by SirDestrox** [comment]
The problems seems to be that on production, the url's don't get unquoted after the request, for some reason that does happen locally.

**Comment by SirDestrox** [comment]
This is likely WSGI or passenger related.

**Comment by SirDestrox** [comment]
See http://stackoverflow.com/questions/31760135/passengerflask-and-url-escaping, this is the fix I will apply.

**Comment by Silox** [comment]
Fixed in https://github.com/ZeusWPI/aichallenge/pull/88
