### ISSUE TITLE
internal server errors when a bot's name is a prefix of another bot

### ISSUE THREAD

**Issue by JensTimmerman** [ZeusWPI/aichallenge#73]
e.g.
have a bot named
a
and a bot named
aa

you get internal server error on 
https://zeus.ugent.be/battlebots/bots/jens/a

**Comment by Silox** [comment]
I could not reproduce this:
https://zeus.ugent.be/battlebots/bots/Silox/Test
https://zeus.ugent.be/battlebots/bots/Silox/Testt
