### ISSUE TITLE
results arent always correctly calculated

### ISSUE THREAD

**Issue by JensTimmerman** [ZeusWPI/aichallenge#77]
why is this a draw: https://zeus.ugent.be/battlebots/matches/65706 ?

**Comment by VandorpeDavid** [comment]
https://zeus.ugent.be/battlebots/matches/65872
Another example. Might be useful for finding reproduction steps.

**Comment by VandorpeDavid** [comment]
This seems to be specific to both Marmoer-bots (when they lose). Both have only draws and wins

**Comment by VandorpeDavid** [comment]
My mistake: only Mamoerbot_v1.1 seems to be causing this.

**Comment by JensTimmerman** [comment]
nope, also here https://zeus.ugent.be/battlebots/matches/66107

**Comment by VandorpeDavid** [comment]
Ever since Java got fixed on the server, that jarbot also only has wins and draws.
